apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: pigallery2
  name: pigallery2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pigallery2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/pigallery-default: "true"
        io.kompose.service: pigallery2
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: bpatrik/pigallery2:latest
          name: pigallery2
          ports:
            - containerPort: 80
              hostPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data/config
              name: pigallery2-claim0
            - mountPath: /app/data/db
              name: pigallery2-claim1
            - mountPath: /app/data/images
              name: pigallery2-claim2
              readOnly: true
            - mountPath: /app/data/tmp
              name: pigallery2-claim3
      restartPolicy: Always
      volumes:
        - name: pigallery2-claim0
          persistentVolumeClaim:
            claimName: pigallery2-claim0
        - name: pigallery2-claim1
          persistentVolumeClaim:
            claimName: pigallery2-claim1
        - name: pigallery2-claim2
          persistentVolumeClaim:
            claimName: pigallery2-claim2
            readOnly: true
        - name: pigallery2-claim3
          persistentVolumeClaim:
            claimName: pigallery2-claim3
