apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tmp
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/pigallery/tmp"
